### PR TITLE
Fix: not show several addresses if only one repeated

### LINKED ISSUE #1395: Wrong fee when confirming send tx
When confirming a send tx the fee is not correct.
In this case the tx was
image

and the confirmation showed

image

### LINKED ISSUE #1397: Wrong several addresses tx
We found a case of a tx that is set as from several addresses but is actually from the same address, but different balances, and the different balances was not clear why.

image

### PR DESCRIPTION
**Pull request by clbartoli**
Some tx where set as several addresses but actually was just one repeated, now it shows only the address
Closes #1397

### CODE REVIEW

File: src/components/Transaction.vue [hunk 1]
```diff
@@ -167,7 +167,8 @@ export default {
   computed: {
     address() {
       if (this.type === 'POSITIVE') {
-        return this.inputs.length > 1
+        return this.inputs.length > 1 &&
+          this.inputs.reduce((acc, input) => input.address !== acc.address)
```
Comment (tmpolaczyk) [inline src/components/Transaction.vue:171]: Here you want to check if there is at least one address different from the first one. You don't need reduce:

```suggestion
          this.inputs.some(input => input.address !== first_address)
```

File: src/components/Transaction.vue [hunk 2]
```diff
@@ -167,7 +167,8 @@ export default {
   computed: {
     address() {
       if (this.type === 'POSITIVE') {
-        return this.inputs.length > 1
+        return this.inputs.length > 1 &&
+          this.inputs.some(input => input.address !== this.inputs[0])
```
Comment (tmpolaczyk) [inline src/components/Transaction.vue:171]:
```suggestion
          this.inputs.some(input => input.address !== this.inputs[0].address)
```

**Review by gabaldon — APPROVED** [review]
