### PR TITLE
fix: validation error in import xprv file

### LINKED ISSUE #1602: Improve XPRV import failure feedback

### PR DESCRIPTION
**Pull request by gabaldon**
close #1602

### CODE REVIEW

File: src/components/steps/ImportXprv.vue [hunk 1]
```diff
@@ -145,11 +146,13 @@ export default {
...
-        return true
-      } else {
-        return false
+    validateXprv(fileInfo) {
+      if (fileInfo) {
+        if (!this.xprvError && fileInfo.master_key) {
+          return true
+        } else {
+          return false
+        }
```
Comment (Tommytrg) [inline src/components/steps/ImportXprv.vue:155]:
```suggestion
      retrurn fileInfo && !this.xprvError && fileInfo.master_key
```

**Review by Tommytrg — CHANGES_REQUESTED** [review]
Refactor validation

**Review by Tommytrg — APPROVED** [review]
