### PR TITLE
fix(hadler): update plain storage with WalletInfo

### LINKED ISSUE #349: fix(handler): encryptWallet handler should update plain storage with WalletInfo
**Describe the bug**

The encryptWallet handler in the main process is the one in charge of creating the wallet from a password, a caption and a seed. The steps that are currently done in order to do this are:

1. Receive password (and caption optionally) from front-end
2. Get seed from unconsolidated data (and generate caption if it was not received in step 1)
3. Initialize a wallet data structure with the given caption (and an id generated at this point from the seed)
4. Initialize wallet AES storage with the password and the generated id
5. Store serialized (encoded) wallet in AES storage
6. Replace wallet storage in the system with current wallet storage
7. Remove unconsolidated wallet from the system

However, these steps are missing the logic that is related to update plain storage with the WalletInfo of the newly created wallet. This is an idea of what should be done:

1-5. Same logic as before.
6. Update plain storage to store the WalletInfo (id and caption) of the newly created wallet.
7. Update array of WalletInfos in the system to contain the new WalletInfo.
8. Replace wallet storage in the system with current wallet storage.
9. Remove unconsolidated wallet from the system.

**To Reproduce**

1. Start Sheikah with `yarn start`
2. Create a new wallet from mnemonics
3. Check that Sheikah successfully redirects to the main wallet page (and a new folder appears at `~/.sheikah/storage`, being the id of the wallet the name of the folder)
3. Close Sheikah
4. Restart Sheikah with `yarn start`
5. Check that Sheikah does not detect any existing wallet

**Expected behavior**

1. Start Sheikah with `yarn start`
2. Create a new wallet from mnemonics
3. Check that Sheikah successfully redirects to the main wallet page (and a new folder appears at `~/.sheikah/storage`, being the id of the wallet the name of the folder)
3. Close Sheikah
4. Restart Sheikah with `yarn start`
5. Check that Sheikah offers the posibility of unlocking the previously created wallet

### PR DESCRIPTION
**Pull request by kronolynx**
- [x] I have read and understood [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood [CONTRIBUTING][cont] document.
- [x] I have read and understood [STYLEGUIDE][style] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] My code is formatted and is accepted by `yarn fmt`.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

### Why this change is necessary and useful
Closes #349

### CODE REVIEW

File: app/main/api/handlers/encryptWallet.ts [hunk 1]
```diff
@@ -113,6 +116,31 @@ async function replaceWallet(
...
+ * @param wallet
+ * @param system
+ */
+async function storePlainInfo(wallet: Wallet, system: AppStorageS & AppStateS) {
+  const walletInfos = asType(
+    system.appStateManager.get("wallets"),
+    Wallets,
+    encryptWalletErrors.UNAVAILABLE_WALLET_INFOS
+  )
+  const infos = {
```
Comment (mmartinbar) [inline app/main/api/handlers/encryptWallet.ts]: I find the name of this variable somewhat confusing (as it contains a field with the same name, infos). I would change it to something more descriptive such as `updatedWalletInfos`

File: test/app/main/api/handlers/encryptWalletFixtures.ts [hunk 2]
```diff
@@ -59,21 +61,39 @@ export const wallet: Wallet = {
...
-/** create inmemory storage */
-export async function inMemoryStorage(args: any):
-  Promise<Storage<Buffer, JsonSerializable, Buffer, Buffer>> {
+/** Create inmemory storage */
+export function inMemoryStorage(cipher: Cipher<Buffer, Buffer>):
+  Storage<Buffer, JsonSerializable, Buffer, Buffer> {
 
+  const keyHasher = sha256BufferHasher
+  const serializer = jsonBufferSerializer
+  // const cipher = new AesCipher(aesSettings)
```
Comment (mmartinbar) [inline test/app/main/api/handlers/encryptWalletFixtures.ts]: Unnecessary comment

File: app/main/api/handlers/encryptWallet.ts [hunk 3]
```diff
@@ -33,15 +34,17 @@ import { config } from "app/common/config"
...
+  system: AppStateS & WalletStorageS & AppStorageS, params: any
+): Promise<JsonSerializable> {
 
   return parseParams(params)
     .then(inject(getUnconsolidatedData, system.appStateManager))
     .then(newWallet)
     .then(inject(newWalletStorage, system.storageFactory))
     .then(storeWallet)
     .then(inject(replaceWallet, system))
+    .then(inject(storePlainInfo, system))
```
Comment (mmartinbar) [inline app/main/api/handlers/encryptWallet.ts]: Again, I have doubts about not reverting actions when errors occur in this promise chain, but that's to be discussed in issue #358, so :+1:

File: test/app/main/api/handlers/encryptWalletFixtures.ts [hunk 4]
```diff
@@ -59,21 +61,39 @@ export const wallet: Wallet = {
...
-  const serializer = jsonBufferSerializer
   const cipher = new AesCipher(aesSettings)
-  const backend = new InMemoryPersister()
 
-  return new Storage(keyHasher, serializer, cipher, backend)
+  return inMemoryStorage(cipher)
+}
+
+/**
+ * Create an inmemory plainStorage
```
Comment (mmartinbar) [inline test/app/main/api/handlers/encryptWalletFixtures.ts]: So good :clap:
