### PR TITLE
Fix redirection when wallet infos are found and time to open the wallet

### LINKED ISSUE #1340: Fix time to open wallet when validating password
The time to show the wallet when writing the password is longer than expected. This should be fixed.

### PR DESCRIPTION
**Pull request by gabaldon**
This pr allows opening the wallet right after the session id is found and also fixes the redirection when the wallet info is found.
close #1340

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -105,8 +105,10 @@ export default new Router({
           }
         } else {
           if (isReady) {
-            store.dispatch('getWalletInfos')
-            if (sessionId) {
+            await store.dispatch('getWalletInfos')
+            const isSessionId = store.state.wallet.sessionId
+            const walletInfos = store.state.wallet.walletInfos
```
Comment (Tommytrg) [inline src/router.js:110]: Could you avoid re-declare this?

**Review by Tommytrg — APPROVED** [review]
