### PR TITLE
fix: disable copy mnemonics in claiming process

### LINKED ISSUE #1372: Fix: disable copy mnemonics
When creating the wallet after the claiming process the seed phrase can be copied and pasted but it shouldn't.

### PR DESCRIPTION
**Pull request by clbartoli**
This PR disable the copy of the seed phrase in the claiming process.

Closes #1372

### CODE REVIEW

File: src/components/claiming/WalletSeedBackup.vue [hunk 1]
```diff
@@ -48,6 +53,9 @@ export default {
         }
       },
     }),
+    disableCopyMnemonics() {
```
Comment (Tommytrg) [inline src/components/claiming/WalletSeedBackup.vue:56]: Could you rename `disableCopyMnemonics` with `isCopyMnemonicsDisabled` here and in
 `src/components/steps/WalletSeedBackup.vue`
```suggestion
    isCopyMnemonicsDisabled() {
```

Comment (clbartoli) [reply src/components/claiming/WalletSeedBackup.vue:56]: sure

**Review by Tommytrg — DISMISSED** [review]

**Review by Tommytrg — APPROVED** [review]
