### PR TITLE
fix: sort transactions by time-lock and creation date

### LINKED ISSUE #1470: Order the transactions with the same timestamp in reverse order
The transactions with the same timestamp should be ordered backward.

### PR DESCRIPTION
**Pull request by gabaldon**
close #1470

### CODE REVIEW

File: src/views/Transactions.vue [hunk 1]
```diff
@@ -41,7 +41,12 @@ export default {
       total: state => state.wallet.balance,
       txLabels: state => state.wallet.txLabels,
       transactions: state =>
-        state.wallet.transactions.sort((t1, t2) => t2.timestamp - t1.timestamp),
+        state.wallet.transactions.sort(
+          (t1, t2) =>
+            t2.timestamp - t1.timestamp ||
+            Number(`${t1.outputs[0].timelock}000`) -
+              Number(`${t2.outputs[0].timelock}000`),
```
Comment (Tommytrg) [inline src/views/Transactions.vue:48]:
```suggestion
            Number(t1.outputs[0].timelock) -
              Number(t2.outputs[0].timelock),
```

**Review by Tommytrg — APPROVED** [review]
