### PR TITLE
Fix redirection in claiming process

### LINKED ISSUE #1369: Claiming_process: close and execute again
Once the claiming process window is closed it can not be opened again 

image

### PR DESCRIPTION
**Pull request by gabaldon**
Fix redirection when the user has completed the claiming process and re-lunch Sheikah.
Fix #1369

### CODE REVIEW

File: src/components/claiming/Countdown.vue [hunk 1]
```diff
@@ -53,7 +53,7 @@
       v-show="exportFileLink"
       ref="file"
       :href="exportFileLink"
-      :download="`${email}-witnet-tokens-claim.json`"
+      :download="download"
```
Comment (Tommytrg) [inline src/components/claiming/Countdown.vue:56]: Why do you replace the name of the file?

File: src/router.js [hunk 2]
```diff
@@ -73,23 +96,22 @@ export default new Router({
...
+                  if (walletInfos && walletInfos.length > 0) {
                     next('/welcome-back/wallet-list')
                   } else {
                     next('/ftu/welcome')
                   }
                 } else {
                   if (!walletInfos || !walletInfos.length) {
                     localStorage.setItem('completed', false)
+                  } else {
+                    localStorage.setItem('completed', true)
```
Comment (Tommytrg) [inline src/router.js:114]: How a user could have a wallet created but `completed` flag as `false`?

File: src/background.js [hunk 3]
```diff
@@ -197,25 +197,25 @@ function createWindow() {
...
+  //         { label: 'ZoomIn', accelerator: 'CmdOrCtrl+Plus', click: () => {} },
+  //         { label: 'Cut', accelerator: 'CmdOrCtrl+X', selector: 'cut:' },
+  //         { label: 'Copy', accelerator: 'CmdOrCtrl+C', selector: 'copy:' },
+  //         { label: 'Paste', accelerator: 'CmdOrCtrl+V', selector: 'paste:' },
+  //       ],
+  //     },
+  //   ])
+
+  //   Menu.setApplicationMenu(menu)
+  // }
```
Comment (clbartoli) [inline src/background.js:218]: I think you forgot to remove it :)

**Review by Tommytrg — APPROVED** [review]
