### PR TITLE
[vue3] Fix inter process communication

### LINKED ISSUE #1878: [vue3]: Fix inter process communication
window is undefined, fixing this issue will fix:

- [x]  Load setup view
- [x]  Handle app shortcuts
- [x]  Fix autoupdater

### PR DESCRIPTION
**Pull request by gabaldon**
- Expose ipcRenderer events to load setup view
- Use auto-updater
- Update loading screen to use Sheikah icon

close #1878

### CODE REVIEW

File: electron/autoUpdaterManager.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+      this.closeWindowAndRestart(actions)
+    })
+
+    autoUpdater.autoDownload = false
+  }
+
+  showDialog() {
+    const options = {
+      type: 'info',
+      title: 'DOClever',
```
Comment (Tommytrg) [inline electron/autoUpdaterManager.ts:35]: What's ` DOClever`?

File: electron/main/index.ts [hunk 2]
```diff
@@ -118,46 +120,20 @@ async function createWindow() {
...
-  sendDownloadedMessage: sendDownloadedMessage,
-  sendDownloadingMessage: sendDownloadingMessage,
-  sendProgressMessage: sendProgressMessage,
-  sendRunningMessage: sendRunningMessage,
-  sendLoadedMessage: sendLoadedMessage,
+  relaunch: relaunch,
   closeWindow: closeWindow,
-  setStatus: setStatus,
-  setWalletPid: setWalletPid,
+  quitApp: quitApp,
```
Comment (Tommytrg) [inline electron/main/index.ts:133]:
```suggestion
  quitApp,
```

File: electron/main/index.ts [hunk 3]
```diff
@@ -118,46 +120,20 @@ async function createWindow() {
...
 }
 
 const actions: Actions = {
-  sendShutdownMessage: sendShutdownMessage,
-  sendDownloadedMessage: sendDownloadedMessage,
-  sendDownloadingMessage: sendDownloadingMessage,
-  sendProgressMessage: sendProgressMessage,
-  sendRunningMessage: sendRunningMessage,
-  sendLoadedMessage: sendLoadedMessage,
+  relaunch: relaunch,
```
Comment (Tommytrg) [inline electron/main/index.ts:131]:
```suggestion
  relaunch,
```

File: electron/main/index.ts [hunk 4]
```diff
@@ -118,46 +120,20 @@ async function createWindow() {
...
   closeWindow: closeWindow,
-  setStatus: setStatus,
-  setWalletPid: setWalletPid,
+  quitApp: quitApp,
+  killWalletProcess: killWalletProcess,
```
Comment (Tommytrg) [inline electron/main/index.ts:134]:
```suggestion
  killWalletProcess,
```

File: electron/main/index.ts [hunk 5]
```diff
@@ -251,24 +219,19 @@ function closeApp(event: Event) {
...
     event.preventDefault()
   }
-  sendShutdownMessage()
-}
-
-function setStatus(s: Status) {
-  status = s
-  loadUrl(status)
+  win?.webContents.send(SHUTDOWN)
+  // window.electron.sendShutdownMessage()
```
Comment (Tommytrg) [inline electron/main/index.ts:223]:
```suggestion
```

File: electron/main/index.ts [hunk 6]
```diff
@@ -251,24 +219,19 @@ function closeApp(event: Event) {
...
 }
 
 // load a url if browser window is ready according to the current status
-function loadUrl(status: Status) {
+function loadUrl() {
   if (win) {
     if (url) {
       // Load the url of the dev server if in development mode
-      win.loadURL(`${url}#/${STATUS_PATH[status]}`)
+      win.loadURL(url)
```
Comment (Tommytrg) [inline electron/main/index.ts:231]: Where's `url` defined?

File: src/global.ts [hunk 7]
```diff
@@ -0,0 +1,16 @@
+export {}
```
Comment (Tommytrg) [inline src/global.ts:1]: If we are only using this file to define types, we can use a `.d.ts` instead of `.ts`

Comment (Tommytrg) [reply src/global.ts:1]: It's also defined [here](https://github.com/witnet/sheikah/pull/1880/files#diff-619cc2239a7eb4ef05041767e6ab0e4fb069e98ee9d2c83c2d8e1865c475e141R10), can we remove this?

File: tsconfig.json [hunk 8]
```diff
@@ -20,7 +20,8 @@
     "noUnusedParameters": true,
     "noFallthroughCasesInSwitch": true,
     "paths": {
-      "@/*": ["./src/*"]
+      "@/*": ["./src/*"],
+      "ipc/*": ["./src/ipc/*"]
```
Comment (Tommytrg) [inline tsconfig.json:24]: Why are we adding ipc to the routes? Personally, I prefer to only have `@` to keep things simple

File: src/views/Setup.vue [hunk 9]
```diff
@@ -12,7 +12,7 @@
             icon="wallet"
           />
           <font-awesome-icon
-            v-if="setupMessage === 'Running wallet'"
+            v-if="setupMessage === 'Running wallet' || !setupMessage"
```
Comment (Tommytrg) [inline src/views/Setup.vue:15]: I'd move this text to a constant. See comment above.

File: src/views/Setup.vue [hunk 10]
```diff
@@ -28,13 +28,13 @@
           <p class="progress-subtitle">
             {{ format(percentage) }}
             <DotsLoading
-              v-if="!synced && theme === THEMES.DARK"
+              v-if="theme === THEMES.DARK"
```
Comment (Tommytrg) [inline src/views/Setup.vue:31]: We could create `color` computed property and move the `if else` logic there to simplify the HTML

**Review by Tommytrg — APPROVED** [review]

File: electron/constants.ts [hunk 11]
```diff
@@ -24,6 +24,13 @@ export const URLS_PUBLIC_WITNET_NODES = [
   '3.21.74.162:21338',
 ]
 
+export const OLD_WITNET_NODE_IPS: Array<string> = [
```
Comment (Tommytrg) [inline electron/constants.ts:27]: I had to check why we still need this IPs. Adding "legacy configuration" to the name may make it easier to understand
```suggestion
export const LEGACY_CONFIGURATION_WITNET_NODE_IPS: Array<string> = [
```

File: src/components/steps/DecryptXprv.vue [hunk 12]
```diff
@@ -99,7 +99,9 @@ export default {
         xprv: this.fileInfo.data.master_key,
         backupPassword: this.password,
       })
+      console.log('error xprv', this.xprvError)
```
Comment (Tommytrg) [inline src/components/steps/DecryptXprv.vue:102]:
```suggestion
```

File: src/components/steps/DecryptXprv.vue [hunk 13]
```diff
@@ -99,7 +99,9 @@ export default {
...
       if (!this.xprvError) {
+        console.log('decrypt', this.fileInfo.data.master_key)
```
Comment (Tommytrg) [inline src/components/steps/DecryptXprv.vue:104]:
```suggestion
```

File: src/types.ts [hunk 14]
```diff
@@ -14,3 +14,10 @@ export interface LanguageDictionary {
   [LocaleCodes.en]: CustomLocale
   [LocaleCodes.es]: CustomLocale
 }
+
+export enum SetupMessages {
+  runningWallet = 'Running wallet',
+  updatingWalletBackend = 'Updating wallet backend',
+  walletUpToDate = 'Wallet up to date',
+  loaded = 'Loaded',
+}
```
Comment (Tommytrg) [inline src/types.ts:23]: I'd avoid using copies here for the UI. We should use this enum to choose the appropriate i18n key.
```suggestion
export enum SetupMessages {
  runningWallet,
  updatingWalletBackend,
  walletUpToDate,
  loaded,
}
```

File: yarn.lock [hunk 15]
```diff
@@ -0,0 +1,15566 @@
+# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
```
Comment (Tommytrg) [inline yarn.lock:1]: Could we delete the `yarn.lock` and add it to the `.gitignore` as we are using `pnpm`?

**Review by Tommytrg — CHANGES_REQUESTED** [review]

File: package.json [hunk 16]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "sheikah-witnet-wallet",
-  "version": "1.11.5",
+  "version": "1.11.9",
```
Comment (Tommytrg) [inline package.json:3]:
```suggestion
  "version": "1.11.5",
```
