### PR TITLE
Fix get tally transaction

### LINKED ISSUE #1484: Tallies returning funds have no `inputs`, leading to `undefined` error in `get_transactions`
**Describe the bug**
Tally transactions with no sufficient commit/reveals will return the funds to the data request creator and the amount will be `POSITIVE`. This will lead to an error while computing the transactions because there are no inputs in tally transactions and `inputs.length` is undefined.

The code in Sheikah for that behaviour is located in `function computeTransactionAddress(inputs, outputs, type)`. :stuck_out_tongue_winking_eye: 

**To Reproduce**
1. Create DR
2. DR has not sufficient commits
3. Sheikah will show an error notification and the transaction list will be empty

### PR DESCRIPTION
**Pull request by gabaldon**
close #1484

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -145,7 +145,6 @@ if (!lock) {
 
 // Exit cleanly on request from parent process in development mode.
 if (isDevelopment) {
-  main()
```
Comment (clbartoli) [inline src/background.js:148]: is this no longer needed?

**Review by clbartoli — APPROVED** [review]
