### PR TITLE
Fix/vue3/build

### LINKED ISSUE #1874: Fix build script in vue3 branch
The build is currently broken in the `vue3` branch. 

- Update `.yml` and test it generates the build for `mac`, `windows` and `linux`

### PR DESCRIPTION
**Pull request by Tommytrg**
- [feat(api): listen to open event in ws connection](https://github.com/witnet/sheikah/pull/1875/commits/65de266f7ccdd5e4a307d17a16ee17965720113f). The `ready` attribute from [rpc-websockets client](https://github.com/elpheria/rpc-websockets/blob/trunk/src/lib/client.ts#L45)
is private and can't be read. We need to fix this to be able to run the build command without typescript errors.
- [fix(ui-compo): update file input type](https://github.com/witnet/sheikah/pull/1875/commits/7f33c05e274ba08f60443935ade740ac3dfc46d5). We have to update the type of the input variable to avoid errors during
the build process
- [style(electron): reorganize imports](https://github.com/witnet/sheikah/pull/1875/commits/bb6fea6e1f96ddb910c587881167acf4d0c673d1)
- [style(types): remove deleted components from type definitions](https://github.com/witnet/sheikah/pull/1875/commits/32fab51f57eebf4d02990db6143b874a0773b82a)
- [chore: update dirname to globalthis](https://github.com/witnet/sheikah/pull/1875/commits/e0318a5cbece95d7c4b4d7f9620a9f08cbbc0493)
- We have to include the dependencies as devDependencies to be inclued in the build: https://github.com/electron-vite/vite-plugin-electron-renderer?tab=readme-ov-file#dependencies-vs-devdependencies
- [ci(build): update ci to use pnpm and update deps](https://github.com/witnet/sheikah/pull/1875/commits/1ab7bbc77982fb862509d9693366af391296febc)
- [chore: update product name](https://github.com/witnet/sheikah/pull/1875/commits/e728635f2c6f0bfdc6bdd09be20627cf202b2e6c)

close #1874

### CODE REVIEW

File: src/api.js [hunk 1]
```diff
@@ -15,11 +15,17 @@ class ApiClient {
   listeners
   options
   ws
+  ready
 
   constructor(options) {
     this.listeners = {}
     this.options = options || defaultOptions
     this.ws = new RPCWebsockets(this.options.url, { ...this.options })
+    this.ready = false
```
Comment (gabaldon) [inline src/api.js:24]: This changes are not related with updating file input type

**Review by gabaldon — COMMENTED** [review]
- [x] Run linter before merging
- [ ] An error appears running the build when logging in:
```release/1.11.5/mac/Sheikah%20Witnet%20wallet.app/Contents/Resources/app.asar/dist/[object%20Object] net::ERR_FILE_NOT_FOUND```

It is probably due to a malformed file path

**Review by gabaldon — APPROVED** [review]
