### PR TITLE
Sidebar collapse animation and CSS form fixes

### LINKED ISSUE #537: Sidebar Collapse as a CSS animation when the UI resizes to tablet
The sidebar should not change the width suddenly when the ui is resizing.
 
Solution: 
The sidebar should change its width smoothly using a css transition, and also the main content should move to the left and own the space left by the sidebar.

### LINKED ISSUE #542: ref(layout): responsive implementation
Implement responsive design for tablet devices.

Solution:
Create media queries to adapt content to the viewport (in case the layout doesn't adapt the components correctly) 
Is related to the issue #541 

close #537 close #541

### LINKED ISSUE #562: Adapt community tab elements to new responsive rules
**Describe the bug**
The elements collapse when the window is tablet size.

**Expected behavior**
The elements should be ordered one below the other when there's no space for each of them.

**Additional context**
#541 #540 #542

### LINKED ISSUE #564: Fix wallet forms CSS
**Describe the problem**
The wallet/receive tab form has lost its flexbox properties and the wallet/send form doesn't have the same styling features like the other forms in the UI.

**Expected behavior**
The wallet/receive form should be vertically positioned and the wallet/send form should look like the other forms in therms of fonts, positioning, etc.

closes #568

### PR DESCRIPTION
**Pull request by kengork**
Thank you for contributing to sheikah! :)

**Please fill in this template (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood [CONTRIBUTING][cont] document.
- [x] I have read and understood [STYLEGUIDE][style] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] My code is formatted and is accepted by `yarn fmt`.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

close #564 close #537 
close #542 close #562 

[Please explain **in detail** why the changes in this PR are needed.]

[code]: https://github.com/witnet/sheikah/blob/master/.github/CODE_OF_CONDUCT.md
[cont]: https://github.com/witnet/sheikah/blob/master/.github/CONTRIBUTING.md
[style]: https://github.com/witnet/sheikah/blob/master/docs/STYLEGUIDE.md

### CODE REVIEW

File: app/renderer/ui/components/main/sections/smartContracts/tabs/history/index.tsx [hunk 1]
```diff
@@ -52,30 +52,29 @@ class TabHistory extends TabComponent<any & Props> {
...
           </Wrapper>
         </div>
-
         <div className={`${styles.right}`}>
           <p className={styles.title}>About Smart Contracts</p>
           <p className={styles.text}>
-            Smart contracts are programs that live in the Witnet blockchain. They have their own
-            addresses for receiving Witnet tokens, but the ability to spend those tokens is
-            determined by the code of the program itself.
+                Smart contracts are programs that live in the Witnet blockchain. They have their own
```
Comment (Tommytrg) [inline app/renderer/ui/components/main/sections/smartContracts/tabs/history/index.tsx]: I think this indentation should be fixed ;)

Comment (kengork) [reply app/renderer/ui/components/main/sections/smartContracts/tabs/history/index.tsx]: done
