### PR TITLE
fix(handler): fix bug when handling errors in getWallet handler

### LINKED ISSUE #433: INVALID_WALLET_TYPE is being wrongly reported as INVALID_PASSWORD
**Describe the bug**
`INVALID_WALLET_TYPE` is being wrongly reported as `INVALID_PASSWORD`.

Bottom line: we are having `INVALID_WALLET_TYPE` errors because some change to the wallet schema recently slipped in.

The issue comes from [line 120 in getWallets.ts](https://github.com/witnet/sheikah/blob/master/app/main/api/handlers/getWallet.ts#L120) catching and re-throwing the error throwed by [line 118](https://github.com/witnet/sheikah/blob/master/app/main/api/handlers/getWallet.ts#L118).

**To Reproduce**
1. Try to unlock a wallet that existed before yesterday.
2. Behold the wrong error.

**Expected behavior**
The error message should match the actual error.

**Desktop (please complete the following information):**
 - OS: GNU/Linux 4.17.5-1-MANJARO #1 SMP PREEMPT
 - Node: v8.9.3
 - Electron: v2.0.8

### PR DESCRIPTION
**Pull request by mmartinbar**
# PR Prelude

Thank you for contributing to sheikah! :)

**Please fill in this template (by putting an `x` inside
the brackets) _before_ filing your PR:**

- [x] I have read and understood [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood [CONTRIBUTING][cont] document.
- [x] I have read and understood [STYLEGUIDE][style] document.
- [x] I have included tests for the changes in my PR. If not, I have included a
  rationale for why I haven't.
- [x] My code is formatted and is accepted by `yarn fmt`.
- [x] **I understand my PR may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

# Why this change is necessary and useful

At the promise chain of the `getWallet` handler, we now have different functions for retrieving the wallet from the database and for validating the type of the retrieved wallet. Fixes #433. 

[code]: https://github.com/witnet/sheikah/blob/master/.github/CODE_OF_CONDUCT.md
[cont]: https://github.com/witnet/sheikah/blob/master/.github/CONTRIBUTING.md
[style]: https://github.com/witnet/sheikah/blob/master/docs/STYLEGUIDE.md

### CODE REVIEW

File: app/main/api/handlers/getWallet.ts [hunk 1]
```diff
@@ -103,25 +105,32 @@ async function replaceStorage(params: GetWalletParams, system: SubSystems)
...
     throw getWalletErrors.INVALID_PASSWORD
   }
 }
 
+/**
+ * validate the type of the wallet in the db
+ * @param {data: JsonSerializable}
+ * @returns {Promise<Wallet>}
+ */
+async function validateWalletType(data: JsonSerializable): Promise<Wallet> {
```
Comment (aesedepece) [inline app/main/api/handlers/getWallet.ts]: I'd fancy this more if it was called `parseWallet` :stuck_out_tongue_winking_eye:

File: app/main/api/handlers/getWallet.ts [hunk 2]
```diff
@@ -103,25 +105,32 @@ async function replaceStorage(params: GetWalletParams, system: SubSystems)
...
-    const data = await storage.get("wallet")
-
-    try {
-      return asRuntimeType(data, Wallet)
-    } catch (error) {
-      throw getWalletErrors.INVALID_WALLET_TYPE
-    }
+    return await storage.get("wallet")
   } catch (error) {
     throw getWalletErrors.INVALID_PASSWORD
```
Comment (aesedepece) [inline app/main/api/handlers/getWallet.ts]: We could take this chance to rename `INVALID_PASSWORD` as `WRONG_PASSWORD`, as the problem is not about validity (conforming to an expected format) but about it being the right one.
